spring.application.name=chatterboxx

spring.data.mongodb.uri=mongodb+srv://pandeyshivamindian_db_user:shivampandey@chatterboxx.lqpiiaq.mongodb.net/chatterboxx?retryWrites=true&w=majority

spring.data.mongodb.database=chatterboxx