spring.application.name=chatterboxx

spring.data.mongodb.uri=mongodb+srv://pandeyshivamindian_db_user:shivampandey@chatterboxx.lqpiiaq.mongodb.net/chatterboxx?retryWrites=true&w=majority

spring.data.mongodb.database=chatterboxx

jwt.secret=Ch@tt3rB0xx#S3cur3K3y!JWT$S1gn1ng^K3y&V3ry*L0ng(Str1ng)F0r#HS256
jwt.expiration=86400000